import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

import 'dart:io';

import '../../../models/destination.dart';
import '../../../repositories/destination_repository.dart';
import '../../../services/cloudinary_service.dart';
import '../../../theme/app_colors.dart';
import '../../../theme/app_spacing.dart';
import '../../../theme/app_text_styles.dart';

class DestinationFormScreen extends StatefulWidget {
  final Destination? destination;

  const DestinationFormScreen({super.key, this.destination});

  @override
  State<DestinationFormScreen> createState() => _DestinationFormScreenState();
}

class _DestinationFormScreenState extends State<DestinationFormScreen> {
  final _formKey = GlobalKey<FormState>();
  final _repository = DestinationRepository();
  final _cloudinaryService = CloudinaryService();

  late TextEditingController _nameController;
  late TextEditingController _shortDescController;
  late TextEditingController _descController;
  late TextEditingController _locationController;
  late TextEditingController _latController;
  late TextEditingController _lngController;
  late TextEditingController _orderController;

  bool _isPopular = false;
  bool _isActive = true;
  String? _imageUrl;
  String? _imagePublicId;
  XFile? _newImageFile;
  bool _isSaving = false;

  @override
  void initState() {
    super.initState();
    final dest = widget.destination;
    _nameController = TextEditingController(text: dest?.name ?? '');
    _shortDescController = TextEditingController(
      text: dest?.shortDescription ?? '',
    );
    _descController = TextEditingController(text: dest?.description ?? '');
    _locationController = TextEditingController(text: dest?.locationName ?? '');
    _latController = TextEditingController(
      text: dest?.latitude?.toString() ?? '',
    );
    _lngController = TextEditingController(
      text: dest?.longitude?.toString() ?? '',
    );
    _orderController = TextEditingController(
      text: dest?.displayOrder.toString() ?? '0',
    );

    _isPopular = dest?.isPopular ?? false;
    _isActive = dest?.isActive ?? true;
    _imageUrl = dest?.imageUrl;
    _imagePublicId = dest?.imagePublicId;
  }

  @override
  void dispose() {
    _nameController.dispose();
    _shortDescController.dispose();
    _descController.dispose();
    _locationController.dispose();
    _latController.dispose();
    _lngController.dispose();
    _orderController.dispose();
    super.dispose();
  }

  Future<void> _pickImage() async {
    final picker = ImagePicker();
    final image = await picker.pickImage(source: ImageSource.gallery);
    if (image != null) {
      setState(() {
        _newImageFile = image;
      });
    }
  }

  Future<void> _save() async {
    if (!_formKey.currentState!.validate()) return;

    if (_imageUrl == null && _newImageFile == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please upload a main image')),
      );
      return;
    }

    setState(() {
      _isSaving = true;
    });

    try {
      String? finalImageUrl = _imageUrl;
      String? finalImagePublicId = _imagePublicId;

      // Upload new image if selected
      if (_newImageFile != null) {
        final uploadedResult = await _cloudinaryService.uploadImage(
          _newImageFile!,
        );
        if (uploadedResult == null) {
          throw Exception('Failed to upload image');
        }
        finalImageUrl = uploadedResult.secureUrl;
        finalImagePublicId = uploadedResult.publicId;
      }

      final now = DateTime.now();

      final destinationData = Destination(
        id:
            widget.destination?.id ??
            '', // Will be generated by repository for new
        name: _nameController.text.trim(),
        shortDescription: _shortDescController.text.trim(),
        description: _descController.text.trim(),
        locationName: _locationController.text.trim(),
        latitude: double.tryParse(_latController.text),
        longitude: double.tryParse(_lngController.text),
        imageUrl: finalImageUrl,
        imagePublicId: finalImagePublicId,
        isPopular: _isPopular,
        isActive: _isActive,
        displayOrder: int.tryParse(_orderController.text) ?? 0,
        createdAt: widget.destination?.createdAt ?? now,
        updatedAt: now,
      );

      if (widget.destination == null) {
        await _repository.createDestination(destinationData);
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Destination created successfully!')),
          );
        }
      } else {
        await _repository.updateDestination(destinationData);

        // If image was replaced, delete the old one from Cloudinary AFTER successful Firestore update
        if (_newImageFile != null && _imagePublicId != null) {
          await _cloudinaryService.deleteImage(_imagePublicId!);
        }

        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Destination updated successfully!')),
          );
        }
      }

      if (mounted) {
        Navigator.of(context).pop();
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('Error saving destination: $e')));
      }
    } finally {
      if (mounted) {
        setState(() {
          _isSaving = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final isEditing = widget.destination != null;

    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        backgroundColor: AppColors.background,
        elevation: 0,
        iconTheme: const IconThemeData(color: AppColors.primaryDark),
        title: Text(
          isEditing ? 'Edit Destination' : 'Add Destination',
          style: AppTextStyles.sectionHeading.copyWith(
            color: AppColors.primaryDark,
          ),
        ),
      ),
      body: Form(
        key: _formKey,
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(AppSpacing.lg),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              _buildSectionTitle('Basic Information'),
              const SizedBox(height: AppSpacing.sm),
              _buildTextField(
                'Destination Name *',
                _nameController,
                required: true,
              ),
              const SizedBox(height: AppSpacing.md),
              _buildTextField(
                'Short Description *',
                _shortDescController,
                required: true,
                maxLines: 2,
              ),
              const SizedBox(height: AppSpacing.md),
              _buildTextField('Full Description', _descController, maxLines: 5),
              const SizedBox(height: AppSpacing.md),

              _buildSectionTitle('Location'),
              const SizedBox(height: AppSpacing.sm),
              _buildTextField(
                'Location Name *',
                _locationController,
                required: true,
              ),
              const SizedBox(height: AppSpacing.md),
              Row(
                children: [
                  Expanded(
                    child: _buildTextField(
                      'Latitude (Optional)',
                      _latController,
                      isNumeric: true,
                    ),
                  ),
                  const SizedBox(width: AppSpacing.md),
                  Expanded(
                    child: _buildTextField(
                      'Longitude (Optional)',
                      _lngController,
                      isNumeric: true,
                    ),
                  ),
                ],
              ),
              const SizedBox(height: AppSpacing.lg),

              _buildSectionTitle('Media'),
              const SizedBox(height: AppSpacing.sm),
              _buildImagePicker(),
              const SizedBox(height: AppSpacing.lg),

              _buildSectionTitle('Settings'),
              const SizedBox(height: AppSpacing.sm),
              _buildTextField(
                'Display Order',
                _orderController,
                isNumeric: true,
              ),
              const SizedBox(height: AppSpacing.md),
              SwitchListTile(
                contentPadding: EdgeInsets.zero,
                title: Text('Mark as Popular', style: AppTextStyles.bodyMedium),
                activeThumbColor: AppColors.primary,
                value: _isPopular,
                onChanged: (val) => setState(() => _isPopular = val),
              ),
              SwitchListTile(
                contentPadding: EdgeInsets.zero,
                title: Text(
                  'Active (Visible to Travelers)',
                  style: AppTextStyles.bodyMedium,
                ),
                activeThumbColor: AppColors.primary,
                value: _isActive,
                onChanged: (val) => setState(() => _isActive = val),
              ),

              const SizedBox(height: AppSpacing.xxl),
              SizedBox(
                width: double.infinity,
                child: ElevatedButton(
                  onPressed: _isSaving ? null : _save,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: AppColors.primary,
                    foregroundColor: Colors.white,
                    padding: const EdgeInsets.symmetric(vertical: 16),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                  child: _isSaving
                      ? const SizedBox(
                          width: 20,
                          height: 20,
                          child: CircularProgressIndicator(
                            color: Colors.white,
                            strokeWidth: 2,
                          ),
                        )
                      : Text(
                          isEditing ? 'Save Changes' : 'Create Destination',
                          style: AppTextStyles.bodyMedium.copyWith(
                            fontWeight: FontWeight.bold,
                            color: Colors.white,
                          ),
                        ),
                ),
              ),
              const SizedBox(height: 40),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildSectionTitle(String title) {
    return Text(
      title,
      style: AppTextStyles.sectionHeading.copyWith(
        color: AppColors.primaryDark,
      ),
    );
  }

  Widget _buildTextField(
    String label,
    TextEditingController controller, {
    bool required = false,
    int maxLines = 1,
    bool isNumeric = false,
  }) {
    return TextFormField(
      controller: controller,
      maxLines: maxLines,
      keyboardType: isNumeric
          ? const TextInputType.numberWithOptions(decimal: true)
          : TextInputType.text,
      decoration: InputDecoration(
        labelText: label,
        filled: true,
        fillColor: AppColors.surface,
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide(
            color: AppColors.border.withValues(alpha: 0.5),
          ),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide(
            color: AppColors.border.withValues(alpha: 0.5),
          ),
        ),
      ),
      validator: required
          ? (value) {
              if (value == null || value.trim().isEmpty) {
                return 'This field is required';
              }
              return null;
            }
          : null,
    );
  }

  Widget _buildImagePicker() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        if (_newImageFile != null)
          Container(
            height: 200,
            width: double.infinity,
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(12),
              image: DecorationImage(
                image: FileImage(File(_newImageFile!.path)),
                fit: BoxFit.cover,
              ),
            ),
          )
        else if (_imageUrl != null)
          Container(
            height: 200,
            width: double.infinity,
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(12),
              image: DecorationImage(
                image: NetworkImage(_imageUrl!),
                fit: BoxFit.cover,
              ),
            ),
          )
        else
          Container(
            height: 120,
            width: double.infinity,
            decoration: BoxDecoration(
              color: AppColors.surface,
              borderRadius: BorderRadius.circular(12),
              border: Border.all(
                color: AppColors.border.withValues(alpha: 0.5),
                style: BorderStyle.solid,
              ),
            ),
            child: const Center(
              child: Icon(
                Icons.add_photo_alternate,
                size: 40,
                color: AppColors.textSecondary,
              ),
            ),
          ),
        const SizedBox(height: AppSpacing.sm),
        OutlinedButton.icon(
          onPressed: _pickImage,
          icon: const Icon(Icons.upload, size: 18),
          label: Text(
            _imageUrl != null || _newImageFile != null
                ? 'Replace Image'
                : 'Upload Image',
          ),
          style: OutlinedButton.styleFrom(
            foregroundColor: AppColors.primary,
            side: const BorderSide(color: AppColors.primary),
          ),
        ),
      ],
    );
  }
}
