// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqcXsfBg7U82g1OpY1n0ZCTa7tYwJ13wU',
    appId: '1:798967339122:web:e9c2c4bed33a60e9fe4aeb',
    messagingSenderId: '798967339122',
    projectId: 'village-tour-sri-lanka',
    authDomain: 'village-tour-sri-lanka.firebaseapp.com',
    storageBucket: 'village-tour-sri-lanka.firebasestorage.app',
    measurementId: 'G-SHGFEPTCLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzwGVKXpSMwS4Bq9x7gNlOo8MaWC2LxJ0',
    appId: '1:798967339122:android:730d3be6667179e4fe4aeb',
    messagingSenderId: '798967339122',
    projectId: 'village-tour-sri-lanka',
    storageBucket: 'village-tour-sri-lanka.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwZ9pbwuVXdZcBSH3miJsj1cW8qY4jHKo',
    appId: '1:798967339122:ios:de8233db8573abb3fe4aeb',
    messagingSenderId: '798967339122',
    projectId: 'village-tour-sri-lanka',
    storageBucket: 'village-tour-sri-lanka.firebasestorage.app',
    iosBundleId: 'com.example.villageTourSriLanka',
  );
}
