import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../../../theme/app_colors.dart';
import '../../../theme/app_spacing.dart';
import '../../../theme/app_text_styles.dart';
import '../../../models/gallery_image.dart';
import '../../../repositories/gallery_repository.dart';
import '../../../services/cloudinary_service.dart';

class AdminAddEditGalleryImageScreen extends StatefulWidget {
  final GalleryImage? image;
  const AdminAddEditGalleryImageScreen({super.key, this.image});

  @override
  State<AdminAddEditGalleryImageScreen> createState() =>
      _AdminAddEditGalleryImageScreenState();
}

class _AdminAddEditGalleryImageScreenState
    extends State<AdminAddEditGalleryImageScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _descController = TextEditingController();
  final _locationController = TextEditingController();

  String _status = 'published';
  String _category = 'Surroundings & Views';
  DateTime? _imageDate;
  List<XFile> _selectedImages = [];
  String? _existingImageUrl;
  bool _isLoading = false;

  final GalleryRepository _galleryRepository = GalleryRepository();
  final CloudinaryService _cloudinaryService = CloudinaryService();

  @override
  void initState() {
    super.initState();
    if (widget.image != null) {
      _titleController.text = widget.image!.title;
      _descController.text = widget.image!.description;
      _locationController.text = widget.image!.location;
      _existingImageUrl = widget.image!.imageUrl;
      _status = widget.image!.status;
      _category = widget.image!.category;
      _imageDate = widget.image!.imageDate;
    }
  }

  @override
  void dispose() {
    _titleController.dispose();
    _descController.dispose();
    _locationController.dispose();
    super.dispose();
  }

  Future<void> _pickImage() async {
    final ImagePicker picker = ImagePicker();
    final List<XFile> images = await picker.pickMultiImage();
    if (images.isNotEmpty) {
      setState(() {
        if (widget.image != null) {
           _selectedImages = [images.first]; // only one if editing
        } else {
           _selectedImages.addAll(images);
        }
      });
    }
  }

  Future<void> _save() async {
    if (!_formKey.currentState!.validate()) return;

    if (_selectedImages.isEmpty && _existingImageUrl == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please select at least one image')),
      );
      return;
    }

    setState(() => _isLoading = true);

    try {
      final user = FirebaseAuth.instance.currentUser;
      final uploaderId = user?.uid ?? 'unknown';

      if (widget.image != null) {
        // Edit mode
        String imageUrl = _existingImageUrl ?? '';
        if (_selectedImages.isNotEmpty) {
          final result = await _cloudinaryService.uploadImage(_selectedImages.first);
          if (result != null) {
            imageUrl = result.secureUrl;
          } else {
            throw Exception('Image upload failed');
          }
        }
        
        final updatedImage = GalleryImage(
          id: widget.image!.id,
          title: _titleController.text.trim(),
          description: _descController.text.trim(),
          imageUrl: imageUrl,
          status: _status,
          category: _category,
          location: _locationController.text.trim(),
          imageDate: _imageDate,
          createdAt: widget.image!.createdAt,
          updatedAt: DateTime.now(),
          uploaderId: widget.image!.uploaderId,
        );
        await _galleryRepository.updateImage(updatedImage);
      } else {
        // Add mode (multiple images)
        for (var image in _selectedImages) {
          final result = await _cloudinaryService.uploadImage(image);
          if (result != null) {
            final newImage = GalleryImage(
              id: '', // Will be generated by Firestore
              title: _titleController.text.trim(), // Shared title
              description: _descController.text.trim(),
              imageUrl: result.secureUrl,
              status: _status,
              category: _category,
              location: _locationController.text.trim(),
              imageDate: _imageDate,
              createdAt: DateTime.now(),
              updatedAt: DateTime.now(),
              uploaderId: uploaderId,
            );
            await _galleryRepository.addImage(newImage);
          } else {
            throw Exception('One or more images failed to upload');
          }
        }
      }

      if (mounted) {
        Navigator.pop(context);
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Gallery image saved successfully!')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $e')),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final isEditing = widget.image != null;

    return Scaffold(
      appBar: AppBar(
        title: Text(isEditing ? 'Edit Image' : 'Add New Image'),
        backgroundColor: AppColors.background,
        elevation: 0,
      ),
      backgroundColor: AppColors.background,
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : SingleChildScrollView(
              padding: const EdgeInsets.all(AppSpacing.lg),
              child: Form(
                key: _formKey,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // Image Picker
                    Center(
                      child: GestureDetector(
                        onTap: _pickImage,
                        child: Container(
                          width: double.infinity,
                          constraints: const BoxConstraints(minHeight: 200),
                          padding: const EdgeInsets.all(8),
                          decoration: BoxDecoration(
                            color: AppColors.surface,
                            borderRadius: BorderRadius.circular(16),
                            border: Border.all(color: AppColors.border),
                          ),
                          child: _selectedImages.isNotEmpty
                              ? Wrap(
                                  spacing: 8,
                                  runSpacing: 8,
                                  children: _selectedImages.map((img) {
                                    return Stack(
                                      children: [
                                        ClipRRect(
                                          borderRadius: BorderRadius.circular(8),
                                          child: Image.file(
                                            File(img.path),
                                            width: 100,
                                            height: 100,
                                            fit: BoxFit.cover,
                                          ),
                                        ),
                                        Positioned(
                                          right: 0,
                                          top: 0,
                                          child: GestureDetector(
                                            onTap: () {
                                              setState(() {
                                                _selectedImages.remove(img);
                                              });
                                            },
                                            child: Container(
                                              padding: const EdgeInsets.all(4),
                                              decoration: BoxDecoration(
                                                color: Colors.black54,
                                                borderRadius: BorderRadius.circular(4),
                                              ),
                                              child: const Icon(Icons.close, color: Colors.white, size: 16),
                                            ),
                                          ),
                                        ),
                                      ],
                                    );
                                  }).toList(),
                                )
                              : _existingImageUrl != null
                                  ? ClipRRect(
                                      borderRadius: BorderRadius.circular(16),
                                      child: Image.network(
                                        _existingImageUrl!,
                                        height: 200,
                                        width: double.infinity,
                                        fit: BoxFit.cover,
                                      ),
                                    )
                                  : Column(
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      children: [
                                        const Icon(
                                          Icons.add_photo_alternate,
                                          size: 48,
                                          color: AppColors.primary,
                                        ),
                                        const SizedBox(height: AppSpacing.sm),
                                        Text(
                                          isEditing ? 'Tap to change image' : 'Tap to upload multiple images',
                                          style: AppTextStyles.bodyMedium.copyWith(
                                            color: AppColors.textSecondary,
                                          ),
                                        ),
                                      ],
                                    ),
                        ),
                      ),
                    ),
                    const SizedBox(height: AppSpacing.xl),

                    // Title
                    TextFormField(
                      controller: _titleController,
                      decoration: const InputDecoration(
                        labelText: 'Title (Optional)',
                        border: OutlineInputBorder(),
                      ),
                    ),
                    const SizedBox(height: AppSpacing.md),

                    // Description
                    TextFormField(
                      controller: _descController,
                      decoration: const InputDecoration(
                        labelText: 'Description (Optional)',
                        border: OutlineInputBorder(),
                      ),
                      maxLines: 3,
                    ),
                    const SizedBox(height: AppSpacing.md),

                    // Location
                    TextFormField(
                      controller: _locationController,
                      decoration: const InputDecoration(
                        labelText: 'Location (Optional)',
                        border: OutlineInputBorder(),
                      ),
                    ),
                    const SizedBox(height: AppSpacing.md),

                    // Category Dropdown
                    DropdownButtonFormField<String>(
                      initialValue: _category,
                      decoration: const InputDecoration(
                        labelText: 'Category',
                        border: OutlineInputBorder(),
                      ),
                      items: const [
                        DropdownMenuItem(value: 'Surroundings & Views', child: Text('Surroundings & Views')),
                        DropdownMenuItem(value: 'Homestay Spaces', child: Text('Homestay Spaces')),
                        DropdownMenuItem(value: 'Activities', child: Text('Activities')),
                        DropdownMenuItem(value: 'Food', child: Text('Food')),
                      ],
                      onChanged: (val) {
                        if (val != null) setState(() => _category = val);
                      },
                    ),
                    const SizedBox(height: AppSpacing.md),

                    // Date Picker
                    InkWell(
                      onTap: () async {
                        final date = await showDatePicker(
                          context: context,
                          initialDate: _imageDate ?? DateTime.now(),
                          firstDate: DateTime(2000),
                          lastDate: DateTime(2100),
                        );
                        if (date != null) {
                          setState(() => _imageDate = date);
                        }
                      },
                      child: InputDecorator(
                        decoration: const InputDecoration(
                          labelText: 'Date (Optional)',
                          border: OutlineInputBorder(),
                        ),
                        child: Text(
                          _imageDate == null 
                            ? 'Select Date' 
                            : '${_imageDate!.year}-${_imageDate!.month.toString().padLeft(2, '0')}-${_imageDate!.day.toString().padLeft(2, '0')}',
                        ),
                      ),
                    ),
                    const SizedBox(height: AppSpacing.md),

                    // Status Dropdown
                    DropdownButtonFormField<String>(
                      initialValue: _status,
                      decoration: const InputDecoration(
                        labelText: 'Status',
                        border: OutlineInputBorder(),
                      ),
                      items: const [
                        DropdownMenuItem(
                          value: 'published',
                          child: Text('Published (Visible to Users)'),
                        ),
                        DropdownMenuItem(
                          value: 'draft',
                          child: Text('Draft (Hidden)'),
                        ),
                      ],
                      onChanged: (val) {
                        if (val != null) setState(() => _status = val);
                      },
                    ),
                    const SizedBox(height: AppSpacing.xxl),

                    // Save Button
                    SizedBox(
                      width: double.infinity,
                      height: 50,
                      child: ElevatedButton(
                        onPressed: _save,
                        style: ElevatedButton.styleFrom(
                          backgroundColor: AppColors.primary,
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(12),
                          ),
                        ),
                        child: Text(
                          'Save Image',
                          style: AppTextStyles.buttonText.copyWith(
                            color: Colors.white,
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
    );
  }
}
